In [ ]:
# DP 기본코드

def maximize_satisfaction(prices, values, budget):
    n = len(prices)

    # dp[i][j]: i번째 상품까지 고려했을 때, 예산이 j일 때의 최대 만족도
    dp = [[0] * (budget + 1) for _ in range(n + 1)]

    # 선택된 상품들을 저장하는 리스트
    selected_items = [[] for _ in range(n + 1)]

    for i in range(1, n + 1):
        for j in range(1, budget + 1):
            # 현재 상품을 예산에 포함할 수 있는 경우
            if int(prices[i - 1]) <= j:  # prices를 정수로 변환하여 사용
                # 상품을 선택할 때와 선택하지 않을 때의 만족도를 비교하여 더 큰 값으로 갱신
                if values[i - 1] + dp[i - 1][j - int(prices[i - 1])] > dp[i - 1][j]:
                    dp[i][j] = values[i - 1] + dp[i - 1][j - int(prices[i - 1])]
                    # 선택된 상품들을 저장
                    selected_items[i] = selected_items[i - 1] + [i]
                else:
                    dp[i][j] = dp[i - 1][j]
                    # 선택되지 않은 경우에는 이전의 선택된 상품들을 그대로 저장
                    selected_items[i] = selected_items[i - 1]
            # 현재 상품을 예산에 포함할 수 없는 경우
            else:
                dp[i][j] = dp[i - 1][j]
                # 선택되지 않은 경우에는 이전의 선택된 상품들을 그대로 저장
                selected_items[i] = selected_items[i - 1]

    return dp[n][budget], selected_items[n]

# 예제 사용
prices = [2.5, 3.5, 5, 6, 15]
values = [97, 97, 98, 100, 99]
budget = 20

result, selected_items = maximize_satisfaction(prices, values, budget)
print(f"최대 만족도: {result}")
print(f"선택된 상품들: {selected_items}")

최대 만족도: 392
선택된 상품들: [1, 2, 3, 4]


In [ ]:
# DP numpy코드
import numpy as np
import pandas as pd

def maximize_satisfaction(prices, values, budget):
    n = len(prices)

    # prices 배열을 정수로 변환
    prices = np.array(prices, dtype=int)
    print(f'prices 배열: {prices}', '\n')

    # dp[i][j]: i번째 상품까지 고려했을 때, 예산이 j일 때의 최대 만족도
    dp = np.zeros((n + 1, budget + 1), dtype=int)
    print(f'초기 dp배열: {dp}', '\n')

    # 각 단계별로 최적해를 저장하는 리스트
    optimal_items_by_step = [[] for _ in range(budget + 1)]

    for i in range(1, n + 1):
        for j in range(1, budget + 1):
            # 현재 상품을 예산에 포함할 수 있는 경우
            if prices[i - 1] <= j:
                # 상품을 선택할 때와 선택하지 않을 때의 만족도 비교하여 더 큰 값으로 갱신
                if values[i - 1] + dp[i - 1, j - prices[i - 1]] > dp[i - 1, j]:
                    dp[i, j] = values[i - 1] + dp[i - 1, j - prices[i - 1]]
                    # 현재 선택된 상품의 번호를 추가
                    optimal_items_by_step[j] = optimal_items_by_step[j - prices[i - 1]] + [i]
                else:
                    dp[i, j] = dp[i - 1, j]
                    # 선택되지 않은 경우에는 이전의 최적해를 그대로 저장
                    optimal_items_by_step[j] = optimal_items_by_step[j]
            # 현재 상품을 예산에 포함할 수 없는 경우
            else:
                dp[i, j] = dp[i - 1, j]
                # 선택되지 않은 경우에는 이전의 최적해를 그대로 저장
                optimal_items_by_step[j] = optimal_items_by_step[j]

        print(f'예산 {j}에서의 최적해: {optimal_items_by_step[j]}')
        print(f'dp 업데이트: {dp}', '\n')
        print('======================================================================================')

    df_dp = pd.DataFrame(dp)
    df_item_by_step = pd.DataFrame(optimal_items_by_step)
    return dp[n, budget], optimal_items_by_step[budget], df_dp, df_item_by_step


In [ ]:
# 예제 적용
prices = [2, 3, 5, 6, 7]
values = [97, 97, 98, 100, 98]
budget = 20

result, selected_items, df_dp, df_item = maximize_satisfaction(prices, values, budget)
print(f"최대 만족도: {result}")
print(f"선택된 상품들: {selected_items}")
display(df_dp)


prices 배열: [2 3 5 6 7] 

초기 dp배열: [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] 

예산 20에서의 최적해: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
dp 업데이트: [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 97 97 97 97 97 97 97 97 97 97 97 97 97 97 97 97 97 97 97]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]] 

예산 20에서의 최적해: [1, 2, 2, 2, 2, 2, 2]
dp 업데이트: [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0  97  97  97  97  97  97  97  97  97  97  97  97  97  97  97  97
   97  97  97]
 [  0   0  97  97

0   1   2   3   4    5    6    7    8    9   ...   11   12   13   14   15  \
0   0   0   0   0   0    0    0    0    0    0  ...    0    0    0    0    0   
1   0   0  97  97  97   97   97   97   97   97  ...   97   97   97   97   97   
2   0   0  97  97  97  194  194  194  194  194  ...  194  194  194  194  194   
3   0   0  97  97  97  194  194  195  195  195  ...  292  292  292  292  292   
4   0   0  97  97  97  194  194  195  197  197  ...  294  294  295  295  295   
5   0   0  97  97  97  194  194  195  197  197  ...  294  294  295  295  295   

    16   17   18   19   20  
0    0    0    0    0    0  
1   97   97   97   97   97  
2  194  194  194  194  194  
3  292  292  292  292  292  
4  392  392  392  392  392  
5  392  392  392  392  393  

[6 rows x 21 columns]

0    1    2    3
0   NaN  NaN  NaN  NaN
1   NaN  NaN  NaN  NaN
2   1.0  NaN  NaN  NaN
3   1.0  NaN  NaN  NaN
4   1.0  1.0  NaN  NaN
5   1.0  2.0  NaN  NaN
6   1.0  2.0  NaN  NaN
7   1.0  3.0  NaN  NaN
8   1.0  4.0  NaN  NaN
9   1.0  4.0  NaN  NaN
10  1.0  2.0  3.0  NaN
11  1.0  2.0  4.0  NaN
12  1.0  2.0  4.0  NaN
13  1.0  3.0  4.0  NaN
14  1.0  4.0  4.0  NaN
15  1.0  4.0  4.0  NaN
16  1.0  2.0  3.0  4.0
17  1.0  2.0  4.0  4.0
18  1.0  2.0  4.0  4.0
19  1.0  3.0  4.0  4.0
20  1.0  3.0  4.0  5.0

In [ ]:
df_dp.to_excel('DP_1.xlsx', index=True)

In [ ]:
prices = [1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 7]
values = [86, 94, 86, 90, 92, 93, 97, 83, 84, 90, 97, 94, 95, 95, 98, 100, 98]
budget = 20

result, selected_items, df_dp, df_item = maximize_satisfaction(prices, values, budget)
print(f"최대 만족도: {result}")
print(f"선택된 상품들: {selected_items}")
display(df_dp)
display(df_item)

prices 배열: [1 1 2 2 2 2 2 3 3 3 3 4 4 5 5 6 7] 

초기 dp배열: [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] 

예산 20에서의 최적해: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
dp 업데이트: [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  

0   1    2    3    4    5    6    7    8    9   ...   11   12   13   14  \
0    0   0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0  86   86   86   86   86   86   86   86   86  ...   86   86   86   86   
2    0  94  180  180  180  180  180  180  180  180  ...  180  180  180  180   
3    0  94  180  180  266  266  266  266  266  266  ...  266  266  266  266   
4    0  94  180  184  270  270  356  356  356  356  ...  356  356  356  356   
5    0  94  180  186  272  276  362  362  448  448  ...  448  448  448  448   
6    0  94  180  187  273  279  365  369  455  455  ...  541  541  541  541   
7    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
8    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
9    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
10   0  94  180  191  277  284  370  376  462  466  ...  552  638  642  642   
11   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
12   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
13   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
14   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
15   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
16   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
17   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   

     15   16   17   18   19   20  
0     0    0    0    0    0    0  
1    86   86   86   86   86   86  
2   180  180  180  180  180  180  
3   266  266  266  266  266  266  
4   356  356  356  356  356  356  
5   448  448  448  448  448  448  
6   541  541  541  541  541  541  
7   638  638  638  638  638  638  
8   721  721  721  721  721  721  
9   722  722  722  805  805  805  
10  728  728  728  812  812  812  
11  735  739  739  825  825  825  
12  735  739  743  825  829  833  
13  735  739  744  825  830  834  
14  735  739  744  825  830  834  
15  735  739  744  825  830  834  
16  735  739  744  825  830  834  
17  735  739  744  825  830  834  

[18 rows x 21 columns]

0    1    2    3     4     5     6     7     8
0   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN
1   2.0  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN
2   2.0  2.0  NaN  NaN   NaN   NaN   NaN   NaN   NaN
3   2.0  7.0  NaN  NaN   NaN   NaN   NaN   NaN   NaN
4   2.0  2.0  7.0  NaN   NaN   NaN   NaN   NaN   NaN
5   2.0  7.0  7.0  NaN   NaN   NaN   NaN   NaN   NaN
6   2.0  2.0  7.0  7.0   NaN   NaN   NaN   NaN   NaN
7   2.0  7.0  7.0  7.0   NaN   NaN   NaN   NaN   NaN
8   2.0  2.0  7.0  7.0   7.0   NaN   NaN   NaN   NaN
9   2.0  2.0  7.0  7.0  11.0   NaN   NaN   NaN   NaN
10  2.0  2.0  7.0  7.0   7.0   7.0   NaN   NaN   NaN
11  2.0  2.0  7.0  7.0   7.0  11.0   NaN   NaN   NaN
12  2.0  2.0  7.0  7.0   7.0   7.0   7.0   NaN   NaN
13  2.0  2.0  7.0  7.0   7.0   7.0  11.0   NaN   NaN
14  2.0  2.0  7.0  7.0   7.0  11.0  11.0   NaN   NaN
15  2.0  2.0  7.0  7.0   7.0   7.0   7.0  11.0   NaN
16  2.0  2.0  7.0  7.0   7.0   7.0  11.0  11.0   NaN
17  2.0  2.0  7.0  7.0   7.0   7.0  11.0  13.0   NaN
18  2.0  2.0  7.0  7.0   7.0   7.0   7.0  11.0  11.0
19  2.0  2.0  7.0  7.0   7.0   7.0   7.0  11.0  13.0
20  2.0  2.0  7.0  7.0   7.0   7.0  11.0  11.0  13.0

In [ ]:
df_dp.to_excel('DP_2.xlsx', index=True)
df_item.to_excel('DP_2_item.xlsx', index=True)

In [ ]:
import numpy as np
import pandas as pd

def maximize_satisfaction(prices, values, budget):
    n = len(prices)

    # prices 배열을 정수로 변환
    prices = np.array(prices, dtype=int)
    print(f'prices 배열: {prices}', '\n')

    # dp[i][j]: i번째 상품까지 고려했을 때, 예산이 j일 때의 최대 만족도
    dp = np.zeros((n + 1, budget + 1), dtype=int)
    print(f'초기 dp 배열: {dp}', '\n')

    # 각 예산별로 최적해를 저장하는 리스트
    optimal_items_by_budget = [[] for _ in range(budget + 1)]

    for i in range(1, n + 1):
        for j in range(1, budget + 1):
            # 현재 상품을 예산에 포함할 수 있는 경우
            if prices[i - 1] <= j:
                # 상품을 선택할 때와 선택하지 않을 때의 만족도 비교하여 더 큰 값으로 갱신
                if values[i - 1] + dp[i - 1, j - prices[i - 1]] > dp[i - 1, j]:
                    dp[i, j] = values[i - 1] + dp[i - 1, j - prices[i - 1]]
                    # 현재 선택된 상품의 번호를 추가
                    optimal_items_by_budget[j] = optimal_items_by_budget[j - prices[i - 1]] + [i]
                else:
                    dp[i, j] = max(dp[i - 1, j], dp[i, j])  # 수정된 부분
                    # 선택되지 않은 경우에는 이전의 최적해를 그대로 저장
                    optimal_items_by_budget[j] = optimal_items_by_budget[j]
            # 현재 상품을 예산에 포함할 수 없는 경우
            else:
                dp[i, j] = dp[i - 1, j]
                # 선택되지 않은 경우에는 이전의 최적해를 그대로 저장
                optimal_items_by_budget[j] = optimal_items_by_budget[j]

        print(f'예산 {j}에서의 최적해: {optimal_items_by_budget[j]}')
        print(f'dp 업데이트: {dp}', '\n')
        print('======================================================================================')

    df_dp = pd.DataFrame(dp)
    df_item_by_budget = pd.DataFrame(optimal_items_by_budget)
    return dp[n, budget], optimal_items_by_budget[budget], df_dp, df_item_by_budget


prices = [1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 7]
values = [86, 94, 86, 90, 92, 93, 97, 83, 84, 90, 97, 94, 95, 95, 98, 100, 98]
budget = 20

result, selected_items, df_dp, df_item = maximize_satisfaction(prices, values, budget)
print(f"최대 만족도: {result}")
print(f"선택된 상품들: {selected_items}")
display(df_dp)

prices 배열: [1 1 2 2 2 2 2 3 3 3 3 4 4 5 5 6 7] 

초기 dp 배열: [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]] 

예산 20에서의 최적해: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
dp 업데이트: [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 

0   1    2    3    4    5    6    7    8    9   ...   11   12   13   14  \
0    0   0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0  86   86   86   86   86   86   86   86   86  ...   86   86   86   86   
2    0  94  180  180  180  180  180  180  180  180  ...  180  180  180  180   
3    0  94  180  180  266  266  266  266  266  266  ...  266  266  266  266   
4    0  94  180  184  270  270  356  356  356  356  ...  356  356  356  356   
5    0  94  180  186  272  276  362  362  448  448  ...  448  448  448  448   
6    0  94  180  187  273  279  365  369  455  455  ...  541  541  541  541   
7    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
8    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
9    0  94  180  191  277  284  370  376  462  466  ...  552  638  638  638   
10   0  94  180  191  277  284  370  376  462  466  ...  552  638  642  642   
11   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
12   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
13   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
14   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
15   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
16   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   
17   0  94  180  191  277  284  370  376  462  467  ...  559  638  649  649   

     15   16   17   18   19   20  
0     0    0    0    0    0    0  
1    86   86   86   86   86   86  
2   180  180  180  180  180  180  
3   266  266  266  266  266  266  
4   356  356  356  356  356  356  
5   448  448  448  448  448  448  
6   541  541  541  541  541  541  
7   638  638  638  638  638  638  
8   721  721  721  721  721  721  
9   722  722  722  805  805  805  
10  728  728  728  812  812  812  
11  735  739  739  825  825  825  
12  735  739  743  825  829  833  
13  735  739  744  825  830  834  
14  735  739  744  825  830  834  
15  735  739  744  825  830  834  
16  735  739  744  825  830  834  
17  735  739  744  825  830  834  

[18 rows x 21 columns]